name: Run Next.js Dev Server with Ngrok

on:
  push:
    branches:
      - main

jobs:
  run-dev:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Recomendado para Next.js 13+

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm install

    # 4. Iniciar el servidor de desarrollo
    - name: Start Dev Server in Background
      run: |
        nohup npm run dev &
        sleep 5 # Esperar que el servidor esté listo

    # 5. Instalar y ejecutar Ngrok
    - name: Install and Start Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list > /dev/null
        sudo apt update && sudo apt install ngrok
        ngrok http 3000 > /dev/null &
        sleep 5
        curl --silent localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    # 6. Imprimir URL pública
    - name: Print Ngrok URL
      run: curl --silent localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
